services:
  app:
    build: .
    image: lucacbittencourt1/laravel-full:latest
    container_name: laravel-full
    entrypoint: ./docker/entrypoint.sh
    restart: always
    ports:
      - 8000:80
      - 443:443
      - 443:443/udp
    volumes:
      - .:/app
      - ./docker/supervisor/supervisord.conf:/usr/local/etc/supervisord.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
